### PR TITLE
Feature scipy optional

### PR DESCRIPTION
**Pull request by mhoffman**
Rationale: if you happen to use CatMAP in an environment where for whatever reason scipy cannot be installed catmap can still be useful for some applications. I.e. the fact that scipy is not installed does not become an immediate showstopper. scipy is always a problematic dependency, but not having it shouldn't stop anyone from using CatMAP completely ...

This seems pretty straightforward and all tests pass with optional scipy blocks. Still, does anyone see any unwanted side-effects?

### CODE REVIEW

**Comment by ajmedford** [comment]
This seems like a good option - less dependencies are better. I had also implemented an option to run without mpmath which I think technically works, but always fails since even test cases seem to need very high precision (or maybe the implementation was just wrong).

It might also be worthwhile to abstract the ASE dependency as much as possible... I think we only use "string2symbols" and the thermochemistry. We could add "string2symbols" to the CatMAP source code, and just raise an error if the user tries to use the ideal gas or harmonic thermo approximation without ASE installed.

**Comment by mhoffman** [comment]
Sure, why not break that out sometimes soon. ase.atoms.string2symbols does not seem to depend on anything. @ajmedford any pointer on where you would like to have it inside catmap? I see you have a catmap.function module already. Does that seem fitting?

**Comment by ajmedford** [comment]
that makes sense to me. There might be some other ASE dependencies I am forgetting about, but I think those are the main ones.

**Comment by mhoffman** [comment]
Ok, I can make ASE optional in a bit but how about merging this feature now?

**Comment by chuanshi** [comment]
If it passes the tests without scipy installed, I'm fine with merging it.  Did you test that this was the case?

**Comment by mhoffman** [comment]
@chuanshi Good point, in two tutorial fail: `electrochemistry/ORR_scaling/mkm_job.py` and `electrochemistry/ORR_thermo/mkm_job`. In both cases because `catmap.model.ReactionModel.map_to_array` calls `catmap.spline` which refers to `scipy.interpolate. InterpolatedUnivariateSpline`. I don't know if there is a clever way to side-step this.

**Comment by chuanshi** [comment]
we could use numpy's 1d interp http://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html as a fallback.  I don't think it's a dropin replacement, but it should be doable without much fuss by changing the map_to_array.

**Pull request merged**
