### PR TITLE
Field Effects

### PR DESCRIPTION
**Pull request by robert-sandberg**
Adds free energy corrections for field effects: enthalpy_entropy.py was changed by adding a homogenous_field function and a local_field_electrochemical function.  The percentage of field-assisted and field-unassisted sites is also defined, which dynamically changes as a function of potential.  Therefore, it was necessary to make changes to min_resid_mapper.py to allow the model to recompile at each point in descriptor space.

### CODE REVIEW

**Comment by ajmedford** [comment]
Does the recompilation happen by default, or only when a field effect correction is applied? It should not happen by default because I expect that it will have a significant impact on the runtime.

In general it should be possible to modify all of the compiled functions to take an extra argument so that it doesn't have to be recompiled at each step... however, this will be easier said than done, so I think that re-compiling at each point in descriptor space is a good work around for now. If someone wants to take this challenge on then let me know and I can consult on the strategy.

**Comment by robert-sandberg** [comment]
The recompilation does not happen by default.  The default is false.  It is true when you call the field effects.

**Comment by ajmedford** [comment]
Cool, that should be good then.

At some point it would be good to add a "kwargs" type argument to all those nasty compiled functions so that it will be easier to add new arguments in the future, but that is a problem for another day.

**Comment by chuanshi** [comment]
Sorry for the extra work, Robert.  Do you mind making sure the indents match for the stuff in your diff? Looking at https://github.com/SUNCAT-Center/catmap/pull/91/files#diff-c6316a398525199f2b89e153c97467f1R60 it looks like everything above the line I've highlighted is using tabs and doesn't align well with the rest of the code, while everything below it looks fine.

**Pull request merged**
